### PR TITLE
246 hcaptcha

### LINKED ISSUE #246: [246] reCAPTCHA
**Current state**
Currently, we are using a reCAPTCHA component that sometimes throws errors at random
We were unable to get reCAPTCHA solutions working, so an alternative seems like the better solution.

**Expected state**
I expect to have a fully functional hCaptcha component with a hCaptcha component, or if that causes issues, we will use a custom hCaptcha component.

**TO DO**
- [ ] Getting the keys
- [ ] Adding hCAPTCHA to register and login
- [ ] Adding hCAPTCHA to the backend

**Necessities**

**Branch**
246-reCAPTCHA (old, attempt 1)
246-recaptcha-v2 (new, attempt 2)
246-hcaptcha (new, attempt 3)

error:
image

### PR DESCRIPTION
**Pull request by jerohero**
closes #246 

<br />

 **What is it supposed to do**  
Adds hCaptcha to verify humans who register and login. This is done through a puzzle that appears every single time. Users can't continue until they succeed.

image

<br />

 **How can we test your branch**  
Unfortunately hCaptcha is a bit of a pain to test, as there are some things you need to do to get it working.

1. Set up the branch as you normally would
2. Modify the backend .env file by adding the following entries:
```
#CURRENT_APP_STATE=dev
CURRENT_APP_STATE=prod
HCAPTCHA_PROD_SECRET_KEY=0xeCC0EA91F78De070a80f3730318055C7e69807B2
HCAPTCHA_DEV_SECRET_KEY=0x0000000000000000000000000000000000000000
```
**NOTE**: When CURRENT_APP_STATE is set to _dev_, hCaptcha is essentially disabled (the captcha will send a valid token without requiring puzzles) so it doesn't hinder development. Set the value to _prod_ to activate it and test its functionality. So make sure it's set to _dev_ when you're not working on captcha!

3. Add a .env file to the frontend folder and add the following entries:
```
#CURRENT_APP_STATE=dev
CURRENT_APP_STATE=prod
HCAPTCHA_PROD_SITE_KEY=031482b3-54e1-4beb-a0d7-dce10eecfdbf
HCAPTCHA_DEV_SITE_KEY=10000000-ffff-ffff-ffff-000000000001
```
**NOTE**: Make sure to restart the React application after making changes to the frontend .env file.

4. Find and open your hosts file; https://docs.rackspace.com/support/how-to/modify-your-hosts-file
4. Add a reference to localhost by adding "_127.0.0.1 seaqull-test.com_" to the hosts file and save it.
5. Visit http://seaqull-test.com:8080/. The application should load and hCaptcha should work on the register and login page.

**FINAL NOTE**: Cookies don't seem to be working on a custom localhost domain. Meaning that functionality like logging out or staying logged in will probably stop working for you.

<br />

 **Additional notes**  
At the moment there's still some doubt about hCaptcha. The puzzle always appearing while logging in is annoying, and the puzzles are irritatingly difficult. At least for now it seems like a good solution until we can get reCAPTCHA working somehow.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

### CODE REVIEW

**Review by ryankroon00 — DISMISSED** [review]

File: frontend/src/stores/defaultData.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ const DefaultDataStore = types
   .model('DefaultDataStore', {
     projectName: types.optional(types.string, 'Seaqull'),
     backendUrl: types.optional(types.string, 'http://localhost:8000/api'),
-    backendUrlBase: types.optional(types.string, 'http://localhost:8000')
+    backendUrlBase: types.optional(types.string, 'http://localhost:8000'),
```
Comment (AjobK) [inline frontend/src/stores/defaultData.js]: Why..?

File: backend/app/controllers/authorizationController.ts [hunk 2]
```diff
@@ -2,6 +2,7 @@ import { Request, Response } from 'express'
 import AccountDAO from '../daos/accountDAO'
 import RoleDAO from '../daos/roleDAO'
 import * as bcrypt from 'bcrypt'
+import captchaService from '../utils/captchaService'
```
Comment (AjobK) [inline backend/app/controllers/authorizationController.ts]:
```suggestion
import CaptchaService from '../utils/captchaService'
```

File: backend/app/controllers/profileController.ts [hunk 3]
```diff
@@ -204,37 +204,38 @@ class ProfileController {
...
 
     errors.password = passwordStrengthErrors
 
-    const isRecaptchaNotValid = await this.checkReCAPTCHA(userRequested.recaptcha)
+    const isCaptchaValid = await captchaService.verifyHCaptcha(captcha)
 
-    if (isRecaptchaNotValid) {
-      errors.recaptcha = [isRecaptchaNotValid]
+    if (!isCaptchaValid) {
+      errors.captcha = ['We could not confirm you are not a robot']
```
Comment (AjobK) [inline backend/app/controllers/profileController.ts]: Why not use push? You already made an array on line 213 and this way you risk losing other pushed error strings.

File: frontend/src/components/registerPrompt/index.js [hunk 4]
```diff
@@ -50,14 +48,13 @@ class RegisterPrompt extends Component {
         this.goToProfile(res.data.user.profile.display_name)
       })
       .catch((res) => {
-        const { username, email, password, recaptcha } = res.response.data.errors
+        const { username, email, password, captcha } = res.response.data.errors
```
Comment (AjobK) [inline frontend/src/components/registerPrompt/index.js]: Maybe use optional chaining, just to be sure

File: frontend/src/components/registerPrompt/index.js [hunk 5]
```diff
@@ -68,62 +65,36 @@ class RegisterPrompt extends Component {
...
-    //   this.setState({
-    //     user_name: null,
-    //     email: null,
-    //     password: null,
-    //     recaptcha: null,
-    //   })
-    // }, 3000);
-  }
+  getError = (credentialError) => {
+    const generalError = this.state.generalError
```
Comment (AjobK) [inline frontend/src/components/registerPrompt/index.js]:
```suggestion
    const { generalError } = this.state
```

**Review by AjobK — CHANGES_REQUESTED** [review]
Check comments

**Comment by AjobK** [comment]
Also cors url

File: frontend/src/stores/defaultData.js (hunk 1 above)
Comment (jerohero) [reply frontend/src/stores/defaultData.js]: I'm glad you asked

I have no idea

File: backend/app/controllers/profileController.ts (hunk 3 above)
Comment (jerohero) [reply backend/app/controllers/profileController.ts]: Just did it the way it was for the other errors. I changed this + the other stuff.

File: frontend/src/components/registerPrompt/index.js (hunk 4 above)
Comment (jerohero) [reply frontend/src/components/registerPrompt/index.js]: Changed it to res.response?.data?.errors

**Comment by jerohero** [comment]
> Also cors url

I removed it (like it used to be) as a custom localhost domain apparently isn't required yet.

File: backend/app/app.ts [hunk 6]
```diff
@@ -28,7 +28,8 @@ const backend = new serverConstructor({
     bodyParser.json(),
     bodyParser.urlencoded({ extended: true }),
     cors({
-      origin: [FRONTEND_URL, 'http://localhost:8080', 'http://localhost:3000', 'http://localhost'],
+      origin: [FRONTEND_URL, 'http://localhost:8080', 'http://localhost:3000', 'http://localhost',
+        'http://seaqull-test.com:8080'],
```
Comment (AjobK) [inline backend/app/app.ts]:
```suggestion
      origin: [
        FRONTEND_URL,
        'http://localhost:8080',
        'http://localhost:3000',
        'http://localhost',
        'http://seaqull-test.com:8080'
      ],
```

This looks a bit better tbh

File: backend/app/utils/captchaService.ts [hunk 7]
```diff
@@ -0,0 +1,23 @@
+import Axios from 'axios'
+
+class captchaService {
+    public static verifyHCaptcha = async (token: string): Promise<boolean> => {
+      const params = new URLSearchParams()
+      params.append('secret', process.env.CURRENT_APP_STATE === 'dev'
```
Comment (AjobK) [inline backend/app/utils/captchaService.ts]: As discussed last sunday this should use the NODE_ENV env attribute. This is a duplicate attribute. We already track if we're on a dev environment

File: backend/app/app.ts (hunk 6 above)
Comment (AjobK) [reply backend/app/app.ts]: Also, you should change the seaqull-test.com to seaqull or just remove it

File: frontend/src/stores/defaultData.js (hunk 1 above)
Comment (AjobK) [reply frontend/src/stores/defaultData.js]: You marked this as resolved but it's not resolve. Please resolve it in code and don't use the 'Resolve convo' button since you might forget certain comments :-) Unless you already made the changes of course.

File: backend/app/utils/captchaService.ts [hunk 8]
```diff
@@ -0,0 +1,23 @@
...
+
+      const config = {
+        headers: {
+          'Content-Type': 'application/x-www-form-urlencoded'
+        }
+      }
+
+      const hCaptcha = await Axios.post('https://hcaptcha.com/siteverify/', params, config)
+
+      return hCaptcha.data['success']
```
Comment (AjobK) [inline backend/app/utils/captchaService.ts:23]: Why not just do

```suggestion
      return hCaptcha.data.success
```

File: backend/app/utils/captchaService.ts [hunk 9]
```diff
@@ -0,0 +1,23 @@
...
+    }
+}
+
+export default captchaService
```
Comment (AjobK) [inline backend/app/utils/captchaService.ts]:
```suggestion
export default CaptchaService
```

File: backend/app/utils/captchaService.ts [hunk 10]
```diff
@@ -0,0 +1,23 @@
+import Axios from 'axios'
+
+class captchaService {
```
Comment (AjobK) [inline backend/app/utils/captchaService.ts]:
```suggestion
class CaptchaService {
```

**Review by AjobK — CHANGES_REQUESTED** [review]

File: frontend/src/stores/defaultData.js (hunk 1 above)
Comment (jerohero) [reply frontend/src/stores/defaultData.js]: Looks like I forgot to push all the changes 🤦‍♂️

**Comment by jerohero** [comment]
Env files changed

**Frontend**
```
HCAPTCHA_PROD_SITE_KEY=031482b3-54e1-4beb-a0d7-dce10eecfdbf
HCAPTCHA_DEV_SITE_KEY=10000000-ffff-ffff-ffff-000000000001
NODE_ENV=development
secure=false
```

**Backend**
```
JWT_SECRET=KGn]FCx0w~TI
JWT_EXPIRATION_TIME=600000
secure=false
HCAPTCHA_PROD_SECRET_KEY=0xeCC0EA91F78De070a80f3730318055C7e69807B2
HCAPTCHA_DEV_SECRET_KEY=0x0000000000000000000000000000000000000000
HCAPTCHA_TEST_TOKEN=10000000-aaaa-bbbb-cccc-000000000001
NODE_ENV=development
```

File: backend/app/utils/captchaService.ts [hunk 11]
```diff
@@ -0,0 +1,23 @@
+import Axios from 'axios'
+
+class CaptchaService {
+    public static verifyHCaptcha = async (token: string): Promise<boolean> => {
+      const params = new URLSearchParams()
+      params.append('secret', process.env.NODE_ENV === 'development'
+        ? process.env.HCAPTCHA_DEV_SECRET_KEY
+        : process.env.HCAPTCHA_PROD_SECRET_KEY)
```
Comment (AjobK) [inline backend/app/utils/captchaService.ts]: Use deconstructor for the keys and extract the ternary to a variable please.

Then append that var.

File: frontend/src/components/loginPrompt/index.js [hunk 12]
```diff
@@ -115,30 +92,29 @@ class LoginPrompt extends Component {
...
-  setElId = (item, id) => {
-    this.elId[item.props.name] = id
+    this.auth(token)
   }
 
-  onChange = (recaptchaToken) => {
-    this.setState({ recaptchaToken })
-    this.auth()
+  onCaptchaError = () => {
+    this.props.store.notification.setContent(popUpData.messages.captchaError)
```
Comment (AjobK) [inline frontend/src/components/loginPrompt/index.js]:
```suggestion
    const { notification } = this.props.store
    const { captchaError } = popUpData.messages

    notification.setContent(captchaError)
```

More readable and less chaining

File: frontend/src/components/loginPrompt/index.js [hunk 13]
```diff
@@ -164,18 +140,21 @@ class LoginPrompt extends Component {
...
-              {/* <ReCAPTCHA
-                ref={this.recaptchaRef}
-                sitekey='6Lev1KUUAAAAAKBHldTqZdeR1XdZDLQiOOgMXJ-S'
-                size='invisible' onChange={this.onChange}
-              /> */}
             </div>
+            <HCaptcha
+              sitekey={ process.env.NODE_ENV === 'development'
+                ? process.env.HCAPTCHA_DEV_SITE_KEY
+                : process.env.HCAPTCHA_PROD_SITE_KEY }
```
Comment (AjobK) [inline frontend/src/components/loginPrompt/index.js]: Same as said before in this PR

File: backend/app/app.ts [hunk 14]
```diff
@@ -30,7 +30,12 @@ const backend = new serverConstructor({
     bodyParser.json(),
     bodyParser.urlencoded({ extended: true }),
     cors({
-      origin: [FRONTEND_URL, 'http://localhost:8080', 'http://localhost:3000', 'http://localhost'],
+      origin: [
+        FRONTEND_URL,
+        'http://localhost:8080',
+        'http://localhost:3000',
+        'http://localhost'
```
Comment (AjobK) [inline backend/app/app.ts]: Maybe there's a more uniform way of doing this? Might even want to extract the `http://localhost`

File: backend/app/controllers/authController.ts [hunk 15]
```diff
@@ -66,6 +67,14 @@ class AuthorizationController {
         remainingTime: Math.floor((account.locked_to - Date.now()) / 1000),
       })
     } else {
+      const isCaptchaValid = await CaptchaService.verifyHCaptcha(captcha)
+
+      if (!isCaptchaValid) {
+        return res.status(403).send({
+          errors: ['We could not confirm you are not a robot']
```
Comment (AjobK) [inline backend/app/controllers/authController.ts]: Is this correct english? I might be wrong lmao

File: backend/app/controllers/profileController.ts [hunk 16]
```diff
@@ -15,6 +14,7 @@ import FileService from '../utils/fileService'
 import Attachment from '../entities/attachment'
 import ProfileFollowedBy from '../entities/profile_followed_by'
 import BanService from '../utils/banService'
+import captchaService from '../utils/captchaService'
```
Comment (AjobK) [inline backend/app/controllers/profileController.ts]:
```suggestion
import CaptchaService from '../utils/CaptchaService'
```

PascalCase

**Review by AjobK — CHANGES_REQUESTED** [review]

File: backend/app/app.ts (hunk 14 above)
Comment (jerohero) [reply backend/app/app.ts]: image
Updated

File: backend/app/controllers/authController.ts (hunk 15 above)
Comment (jerohero) [reply backend/app/controllers/authController.ts]: I have gechange to the _We couldn't verify that you're not a robot._

**Review by AjobK — CHANGES_REQUESTED** [review]
**Captcha**
image

**Result**
image

Doesn't seem to work? I have my .env enabled with 'development', which I shouldn't trigger a captcha or it should work.

**Review by AjobK — APPROVED** [review]
